### ISSUE TITLE
PropertyConfigurator istream interface

### ISSUE THREAD

**Issue by skypexu** [orocos-toolchain/log4cpp#10]
Why does not PropertyConfigurator provide a function to read from an istream ?

**Comment by meyerj** [comment]
Sorry, but this repo is only a patched fork of log4cpp to be used in the Orocos project and we are only using a small subset of features. For those kind of questions it would be better to post them at https://sourceforge.net/p/log4cpp/discussion/.

But generally spoken an interface that offers to read a configuration from `std::istream` is more generic than if it would only provide a method to pass a filename. An `istream` can be anything that can be read sequentially, for example another string or a socket.
